swagger: "2.0"
info:
  title: Backup Handler Service
  description: A service to handle backup for Pachyderm object
  version: ""
host: localhost:8890
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /backups:
    put:
      tags:
      - Backup Service
      summary: update Backup Service
      description: Update backup request
      operationId: Backup Service#update
      parameters:
      - name: UpdateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/BackupServiceUpdateRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/BackupServiceUpdateResponseBody'
        "404":
          description: Error is returned when backup is not found
          schema:
            $ref: '#/definitions/BackupServiceUpdateBackupNotFoundResponseBody'
            required:
            - message
      schemes:
      - http
    post:
      tags:
      - Backup Service
      summary: create Backup Service
      description: New backup request
      operationId: Backup Service#create
      parameters:
      - name: CreateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/BackupServiceCreateRequestBody'
      responses:
        "202":
          description: Accepted response.
          schema:
            $ref: '#/definitions/BackupServiceCreateResponseBody'
      schemes:
      - http
  /backups/{id}:
    get:
      tags:
      - Backup Service
      summary: get Backup Service
      description: Obtain backup request
      operationId: Backup Service#get
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/BackupServiceGetResponseBody'
        "404":
          description: Error is returned when backup is not found
          schema:
            $ref: '#/definitions/BackupServiceGetBackupNotFoundResponseBody'
            required:
            - message
      schemes:
      - http
    delete:
      tags:
      - Backup Service
      summary: delete Backup Service
      description: Mark complete backup request
      operationId: Backup Service#delete
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/BackupServiceDeleteResponseBody'
        "404":
          description: Error is returned when backup is not found
          schema:
            $ref: '#/definitions/BackupServiceDeleteBackupNotFoundResponseBody'
            required:
            - message
      schemes:
      - http
  /openapi3.json:
    get:
      tags:
      - Restore Service
      summary: Download ./gen/http/openapi3.json
      operationId: Restore Service#/openapi3.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /restores:
    put:
      tags:
      - Restore Service
      summary: update Restore Service
      description: Update restore request
      operationId: Restore Service#update
      parameters:
      - name: UpdateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/RestoreServiceUpdateRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/RestoreServiceUpdateResponseBody'
      schemes:
      - http
    post:
      tags:
      - Restore Service
      summary: create Restore Service
      description: New restore request
      operationId: Restore Service#create
      parameters:
      - name: CreateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/RestoreServiceCreateRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/RestoreServiceCreateResponseBody'
        "404":
          description: Error is returned when backup location is not found
          schema:
            $ref: '#/definitions/RestoreServiceCreateBackupNotFoundResponseBody'
            required:
            - message
      schemes:
      - http
  /restores/{id}:
    get:
      tags:
      - Restore Service
      summary: get Restore Service
      description: Get restore request
      operationId: Restore Service#get
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/RestoreServiceGetResponseBody'
      schemes:
      - http
    delete:
      tags:
      - Restore Service
      summary: delete Restore Service
      description: Mark complete restore request
      operationId: Restore Service#delete
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/RestoreServiceDeleteResponseBody'
      schemes:
      - http
definitions:
  BackupServiceCreateRequestBody:
    title: BackupServiceCreateRequestBody
    type: object
    properties:
      command:
        type: string
        description: base64 encoded command to run in pod
        example: hostname -f
      container:
        type: string
        description: Name of container in pod
        example: pachd
      kubernetes_resource:
        type: string
        description: base64 encoded json representation of object
        example: '{"kind":"Pachyderm",...}'
      name:
        type: string
        description: Name of pachyderm instance backed up
        example: pachdyderm-sample
      namespace:
        type: string
        description: Namespace of resource backed up
        example: testing
      pod:
        type: string
        description: Name of target pod
        example: pachd-65734594-sdg46
      storage_secret:
        type: string
        description: Kubernetes secret containing S3 storage credentials
        example: example-aws-secret
    example:
      command: hostname -f
      container: pachd
      kubernetes_resource: '{"kind":"Pachyderm",...}'
      name: pachdyderm-sample
      namespace: testing
      pod: pachd-65734594-sdg46
      storage_secret: example-aws-secret
  BackupServiceCreateResponseBody:
    title: 'Mediatype identifier: backupresult; view=default'
    type: object
    properties:
      command:
        type: string
        description: base64 encoded command to run in pod
        example: hostname -f
      container:
        type: string
        description: Name of container in pod
        example: pachd
      created_at:
        type: string
        example: "2019-10-12 07:20:50.52"
      deleted_at:
        type: string
        example: "2019-10-12 07:20:54.52"
      id:
        type: string
        example: 00000-090000-0000000-000000
      kubernetes_resource:
        type: string
        description: base64 encoded json representation of object
        example: '{"kind":"Pachyderm",...}'
      location:
        type: string
        description: URL of the uploaded backup tarball
        example: http://minio.local/backups/pachyderm-backup.tar.gz
      name:
        type: string
        description: Name of pachyderm instance backed up
        example: pachdyderm-sample
      namespace:
        type: string
        description: Namespace of resource backed up
        example: testing
      pod:
        type: string
        description: Name of target pod
        example: pachd-65734594-sdg46
      state:
        type: string
        description: Current state of the job
        example: completed
        enum:
        - queued
        - running
        - completed
      storage_secret:
        type: string
        description: Kubernetes secret containing S3 storage credentials
        example: example-aws-secret
      updated_at:
        type: string
        example: "2019-10-12 07:20:52.52"
    description: CreateResponseBody result type (default view)
    example:
      command: hostname -f
      container: pachd
      created_at: "2019-10-12 07:20:50.52"
      deleted_at: "2019-10-12 07:20:54.52"
      id: 00000-090000-0000000-000000
      kubernetes_resource: '{"kind":"Pachyderm",...}'
      location: http://minio.local/backups/pachyderm-backup.tar.gz
      name: pachdyderm-sample
      namespace: testing
      pod: pachd-65734594-sdg46
      state: running
      storage_secret: example-aws-secret
      updated_at: "2019-10-12 07:20:52.52"
  BackupServiceDeleteBackupNotFoundResponseBody:
    title: BackupServiceDeleteBackupNotFoundResponseBody
    type: object
    properties:
      message:
        type: string
        description: backup resource not found
        example: Quis odio quae laudantium repudiandae quas ea.
    description: backup not found
    example:
      message: Est repellat voluptatibus esse.
    required:
    - message
  BackupServiceDeleteResponseBody:
    title: 'Mediatype identifier: backupresult; view=default'
    type: object
    properties:
      command:
        type: string
        description: base64 encoded command to run in pod
        example: hostname -f
      container:
        type: string
        description: Name of container in pod
        example: pachd
      created_at:
        type: string
        example: "2019-10-12 07:20:50.52"
      deleted_at:
        type: string
        example: "2019-10-12 07:20:54.52"
      id:
        type: string
        example: 00000-090000-0000000-000000
      kubernetes_resource:
        type: string
        description: base64 encoded json representation of object
        example: '{"kind":"Pachyderm",...}'
      location:
        type: string
        description: URL of the uploaded backup tarball
        example: http://minio.local/backups/pachyderm-backup.tar.gz
      name:
        type: string
        description: Name of pachyderm instance backed up
        example: pachdyderm-sample
      namespace:
        type: string
        description: Namespace of resource backed up
        example: testing
      pod:
        type: string
        description: Name of target pod
        example: pachd-65734594-sdg46
      state:
        type: string
        description: Current state of the job
        example: completed
        enum:
        - queued
        - running
        - completed
      storage_secret:
        type: string
        description: Kubernetes secret containing S3 storage credentials
        example: example-aws-secret
      updated_at:
        type: string
        example: "2019-10-12 07:20:52.52"
    description: DeleteResponseBody result type (default view)
    example:
      command: hostname -f
      container: pachd
      created_at: "2019-10-12 07:20:50.52"
      deleted_at: "2019-10-12 07:20:54.52"
      id: 00000-090000-0000000-000000
      kubernetes_resource: '{"kind":"Pachyderm",...}'
      location: http://minio.local/backups/pachyderm-backup.tar.gz
      name: pachdyderm-sample
      namespace: testing
      pod: pachd-65734594-sdg46
      state: running
      storage_secret: example-aws-secret
      updated_at: "2019-10-12 07:20:52.52"
  BackupServiceGetBackupNotFoundResponseBody:
    title: BackupServiceGetBackupNotFoundResponseBody
    type: object
    properties:
      message:
        type: string
        description: backup resource not found
        example: Voluptatibus laudantium dolores ducimus.
    description: backup not found
    example:
      message: Et laborum in est.
    required:
    - message
  BackupServiceGetResponseBody:
    title: 'Mediatype identifier: backupresult; view=default'
    type: object
    properties:
      command:
        type: string
        description: base64 encoded command to run in pod
        example: hostname -f
      container:
        type: string
        description: Name of container in pod
        example: pachd
      created_at:
        type: string
        example: "2019-10-12 07:20:50.52"
      deleted_at:
        type: string
        example: "2019-10-12 07:20:54.52"
      id:
        type: string
        example: 00000-090000-0000000-000000
      kubernetes_resource:
        type: string
        description: base64 encoded json representation of object
        example: '{"kind":"Pachyderm",...}'
      location:
        type: string
        description: URL of the uploaded backup tarball
        example: http://minio.local/backups/pachyderm-backup.tar.gz
      name:
        type: string
        description: Name of pachyderm instance backed up
        example: pachdyderm-sample
      namespace:
        type: string
        description: Namespace of resource backed up
        example: testing
      pod:
        type: string
        description: Name of target pod
        example: pachd-65734594-sdg46
      state:
        type: string
        description: Current state of the job
        example: completed
        enum:
        - queued
        - running
        - completed
      storage_secret:
        type: string
        description: Kubernetes secret containing S3 storage credentials
        example: example-aws-secret
      updated_at:
        type: string
        example: "2019-10-12 07:20:52.52"
    description: GetResponseBody result type (default view)
    example:
      command: hostname -f
      container: pachd
      created_at: "2019-10-12 07:20:50.52"
      deleted_at: "2019-10-12 07:20:54.52"
      id: 00000-090000-0000000-000000
      kubernetes_resource: '{"kind":"Pachyderm",...}'
      location: http://minio.local/backups/pachyderm-backup.tar.gz
      name: pachdyderm-sample
      namespace: testing
      pod: pachd-65734594-sdg46
      state: queued
      storage_secret: example-aws-secret
      updated_at: "2019-10-12 07:20:52.52"
  BackupServiceUpdateBackupNotFoundResponseBody:
    title: BackupServiceUpdateBackupNotFoundResponseBody
    type: object
    properties:
      message:
        type: string
        description: backup resource not found
        example: Ipsam est aut occaecati.
    description: backup not found
    example:
      message: Tenetur delectus dolorem quas et aspernatur labore.
    required:
    - message
  BackupServiceUpdateRequestBody:
    title: BackupServiceUpdateRequestBody
    type: object
    properties:
      command:
        type: string
        description: base64 encoded command to run in pod
        example: hostname -f
      container:
        type: string
        description: Name of container in pod
        example: pachd
      created_at:
        type: string
        example: "2019-10-12 07:20:50.52"
      deleted_at:
        type: string
        example: "2019-10-12 07:20:54.52"
      id:
        type: string
        example: 00000-090000-0000000-000000
      kubernetes_resource:
        type: string
        description: base64 encoded json representation of object
        example: '{"kind":"Pachyderm",...}'
      location:
        type: string
        description: URL of the uploaded backup tarball
        example: http://minio.local/backups/pachyderm-backup.tar.gz
      name:
        type: string
        description: Name of pachyderm instance backed up
        example: pachdyderm-sample
      namespace:
        type: string
        description: Namespace of resource backed up
        example: testing
      pod:
        type: string
        description: Name of target pod
        example: pachd-65734594-sdg46
      state:
        type: string
        description: Current state of the job
        example: completed
        enum:
        - queued
        - running
        - completed
      storage_secret:
        type: string
        description: Kubernetes secret containing S3 storage credentials
        example: example-aws-secret
      updated_at:
        type: string
        example: "2019-10-12 07:20:52.52"
    example:
      command: hostname -f
      container: pachd
      created_at: "2019-10-12 07:20:50.52"
      deleted_at: "2019-10-12 07:20:54.52"
      id: 00000-090000-0000000-000000
      kubernetes_resource: '{"kind":"Pachyderm",...}'
      location: http://minio.local/backups/pachyderm-backup.tar.gz
      name: pachdyderm-sample
      namespace: testing
      pod: pachd-65734594-sdg46
      state: running
      storage_secret: example-aws-secret
      updated_at: "2019-10-12 07:20:52.52"
  BackupServiceUpdateResponseBody:
    title: 'Mediatype identifier: backupresult; view=default'
    type: object
    properties:
      command:
        type: string
        description: base64 encoded command to run in pod
        example: hostname -f
      container:
        type: string
        description: Name of container in pod
        example: pachd
      created_at:
        type: string
        example: "2019-10-12 07:20:50.52"
      deleted_at:
        type: string
        example: "2019-10-12 07:20:54.52"
      id:
        type: string
        example: 00000-090000-0000000-000000
      kubernetes_resource:
        type: string
        description: base64 encoded json representation of object
        example: '{"kind":"Pachyderm",...}'
      location:
        type: string
        description: URL of the uploaded backup tarball
        example: http://minio.local/backups/pachyderm-backup.tar.gz
      name:
        type: string
        description: Name of pachyderm instance backed up
        example: pachdyderm-sample
      namespace:
        type: string
        description: Namespace of resource backed up
        example: testing
      pod:
        type: string
        description: Name of target pod
        example: pachd-65734594-sdg46
      state:
        type: string
        description: Current state of the job
        example: completed
        enum:
        - queued
        - running
        - completed
      storage_secret:
        type: string
        description: Kubernetes secret containing S3 storage credentials
        example: example-aws-secret
      updated_at:
        type: string
        example: "2019-10-12 07:20:52.52"
    description: UpdateResponseBody result type (default view)
    example:
      command: hostname -f
      container: pachd
      created_at: "2019-10-12 07:20:50.52"
      deleted_at: "2019-10-12 07:20:54.52"
      id: 00000-090000-0000000-000000
      kubernetes_resource: '{"kind":"Pachyderm",...}'
      location: http://minio.local/backups/pachyderm-backup.tar.gz
      name: pachdyderm-sample
      namespace: testing
      pod: pachd-65734594-sdg46
      state: running
      storage_secret: example-aws-secret
      updated_at: "2019-10-12 07:20:52.52"
  RestoreServiceCreateBackupNotFoundResponseBody:
    title: RestoreServiceCreateBackupNotFoundResponseBody
    type: object
    properties:
      message:
        type: string
        description: backup resource not found
        example: Sunt eum mollitia accusantium.
    description: backup not found
    example:
      message: Mollitia adipisci.
    required:
    - message
  RestoreServiceCreateRequestBody:
    title: RestoreServiceCreateRequestBody
    type: object
    properties:
      backup_location:
        type: string
        description: Key of backup tarball
        example: pachyderm-backup.tar.gz
      name:
        type: string
        description: Name of pachyderm instance to restore to
        example: pachdyderm-sample
      namespace:
        type: string
        description: Namespace to restore to
        example: testing
      storage_secret:
        type: string
        description: Kubernetes secret containing S3 storage credentials
        example: example-aws-secret
    example:
      backup_location: pachyderm-backup.tar.gz
      name: pachdyderm-sample
      namespace: testing
      storage_secret: example-aws-secret
  RestoreServiceCreateResponseBody:
    title: 'Mediatype identifier: restoreresult; view=default'
    type: object
    properties:
      backup_location:
        type: string
        description: Key of backup tarball
        example: pachyderm-backup.tar.gz
      created_at:
        type: string
        example: "2019-10-12 07:20:50.52"
      database:
        type: string
        description: base64 encoded database dump
        example: database.sql
      deleted_at:
        type: string
        example: "2019-10-12 07:20:54.52"
      id:
        type: string
        example: 00000-090000-0000000-000000
      kubernetes_resource:
        type: string
        description: base64 encoded kubernetes object
        example: pachyderm.yaml
      name:
        type: string
        description: Name of pachyderm instance to restore to
        example: pachdyderm-sample
      namespace:
        type: string
        description: Namespace to restore to
        example: testing
      storage_secret:
        type: string
        description: Kubernetes secret containing S3 storage credentials
        example: example-aws-secret
      updated_at:
        type: string
        example: "2019-10-12 07:20:52.52"
    description: CreateResponseBody result type (default view)
    example:
      backup_location: pachyderm-backup.tar.gz
      created_at: "2019-10-12 07:20:50.52"
      database: database.sql
      deleted_at: "2019-10-12 07:20:54.52"
      id: 00000-090000-0000000-000000
      kubernetes_resource: pachyderm.yaml
      name: pachdyderm-sample
      namespace: testing
      storage_secret: example-aws-secret
      updated_at: "2019-10-12 07:20:52.52"
  RestoreServiceDeleteResponseBody:
    title: 'Mediatype identifier: restoreresult; view=default'
    type: object
    properties:
      backup_location:
        type: string
        description: Key of backup tarball
        example: pachyderm-backup.tar.gz
      created_at:
        type: string
        example: "2019-10-12 07:20:50.52"
      database:
        type: string
        description: base64 encoded database dump
        example: database.sql
      deleted_at:
        type: string
        example: "2019-10-12 07:20:54.52"
      id:
        type: string
        example: 00000-090000-0000000-000000
      kubernetes_resource:
        type: string
        description: base64 encoded kubernetes object
        example: pachyderm.yaml
      name:
        type: string
        description: Name of pachyderm instance to restore to
        example: pachdyderm-sample
      namespace:
        type: string
        description: Namespace to restore to
        example: testing
      storage_secret:
        type: string
        description: Kubernetes secret containing S3 storage credentials
        example: example-aws-secret
      updated_at:
        type: string
        example: "2019-10-12 07:20:52.52"
    description: DeleteResponseBody result type (default view)
    example:
      backup_location: pachyderm-backup.tar.gz
      created_at: "2019-10-12 07:20:50.52"
      database: database.sql
      deleted_at: "2019-10-12 07:20:54.52"
      id: 00000-090000-0000000-000000
      kubernetes_resource: pachyderm.yaml
      name: pachdyderm-sample
      namespace: testing
      storage_secret: example-aws-secret
      updated_at: "2019-10-12 07:20:52.52"
  RestoreServiceGetResponseBody:
    title: 'Mediatype identifier: restoreresult; view=default'
    type: object
    properties:
      backup_location:
        type: string
        description: Key of backup tarball
        example: pachyderm-backup.tar.gz
      created_at:
        type: string
        example: "2019-10-12 07:20:50.52"
      database:
        type: string
        description: base64 encoded database dump
        example: database.sql
      deleted_at:
        type: string
        example: "2019-10-12 07:20:54.52"
      id:
        type: string
        example: 00000-090000-0000000-000000
      kubernetes_resource:
        type: string
        description: base64 encoded kubernetes object
        example: pachyderm.yaml
      name:
        type: string
        description: Name of pachyderm instance to restore to
        example: pachdyderm-sample
      namespace:
        type: string
        description: Namespace to restore to
        example: testing
      storage_secret:
        type: string
        description: Kubernetes secret containing S3 storage credentials
        example: example-aws-secret
      updated_at:
        type: string
        example: "2019-10-12 07:20:52.52"
    description: GetResponseBody result type (default view)
    example:
      backup_location: pachyderm-backup.tar.gz
      created_at: "2019-10-12 07:20:50.52"
      database: database.sql
      deleted_at: "2019-10-12 07:20:54.52"
      id: 00000-090000-0000000-000000
      kubernetes_resource: pachyderm.yaml
      name: pachdyderm-sample
      namespace: testing
      storage_secret: example-aws-secret
      updated_at: "2019-10-12 07:20:52.52"
  RestoreServiceUpdateRequestBody:
    title: RestoreServiceUpdateRequestBody
    type: object
    properties:
      backup_location:
        type: string
        description: Key of backup tarball
        example: pachyderm-backup.tar.gz
      created_at:
        type: string
        example: "2019-10-12 07:20:50.52"
      database:
        type: string
        description: base64 encoded database dump
        example: database.sql
      deleted_at:
        type: string
        example: "2019-10-12 07:20:54.52"
      id:
        type: string
        example: 00000-090000-0000000-000000
      kubernetes_resource:
        type: string
        description: base64 encoded kubernetes object
        example: pachyderm.yaml
      name:
        type: string
        description: Name of pachyderm instance to restore to
        example: pachdyderm-sample
      namespace:
        type: string
        description: Namespace to restore to
        example: testing
      storage_secret:
        type: string
        description: Kubernetes secret containing S3 storage credentials
        example: example-aws-secret
      updated_at:
        type: string
        example: "2019-10-12 07:20:52.52"
    example:
      backup_location: pachyderm-backup.tar.gz
      created_at: "2019-10-12 07:20:50.52"
      database: database.sql
      deleted_at: "2019-10-12 07:20:54.52"
      id: 00000-090000-0000000-000000
      kubernetes_resource: pachyderm.yaml
      name: pachdyderm-sample
      namespace: testing
      storage_secret: example-aws-secret
      updated_at: "2019-10-12 07:20:52.52"
  RestoreServiceUpdateResponseBody:
    title: 'Mediatype identifier: restoreresult; view=default'
    type: object
    properties:
      backup_location:
        type: string
        description: Key of backup tarball
        example: pachyderm-backup.tar.gz
      created_at:
        type: string
        example: "2019-10-12 07:20:50.52"
      database:
        type: string
        description: base64 encoded database dump
        example: database.sql
      deleted_at:
        type: string
        example: "2019-10-12 07:20:54.52"
      id:
        type: string
        example: 00000-090000-0000000-000000
      kubernetes_resource:
        type: string
        description: base64 encoded kubernetes object
        example: pachyderm.yaml
      name:
        type: string
        description: Name of pachyderm instance to restore to
        example: pachdyderm-sample
      namespace:
        type: string
        description: Namespace to restore to
        example: testing
      storage_secret:
        type: string
        description: Kubernetes secret containing S3 storage credentials
        example: example-aws-secret
      updated_at:
        type: string
        example: "2019-10-12 07:20:52.52"
    description: UpdateResponseBody result type (default view)
    example:
      backup_location: pachyderm-backup.tar.gz
      created_at: "2019-10-12 07:20:50.52"
      database: database.sql
      deleted_at: "2019-10-12 07:20:54.52"
      id: 00000-090000-0000000-000000
      kubernetes_resource: pachyderm.yaml
      name: pachdyderm-sample
      namespace: testing
      storage_secret: example-aws-secret
      updated_at: "2019-10-12 07:20:52.52"
